---
  - name: Install Postgres database packages.
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items:
    - postgresql
    - postgresql-server-dev-all

  - name: Setup Postgres database
    postgresql_db: name={{ project_user }}
    sudo: yes
    sudo_user: postgres

  - name: Postgres user access to database
    postgresql_user: db={{ project_user }} name={{ project_user }} priv=ALL
    sudo: yes
    sudo_user: postgres
    notify: restart postgres